<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Map2Resource</AssemblyName>
    <RootNamespace>Map2Resource</RootNamespace>
    <AssemblyTitle>Map2Resource</AssemblyTitle>
    <Description>Converts Map Editor XML maps into GTA Network server map resources.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\GTANetworkShared.csproj" />
  </ItemGroup>

</Project>
