#!/usr/bin/env python3
"""Regenerates Core/NativeHashes.g.cs from ../source/core/NativeHashes.hpp."""
import os
here = os.path.dirname(os.path.abspath(__file__))
src = open(os.path.join(here, '..', 'source', 'core', 'NativeHashes.hpp'), encoding='utf-8', errors='replace').read()
out = ['// <auto-generated>',
       '// Generated from Shv.NET/source/core/NativeHashes.hpp by Shv.NET/ref/generate-hashes.py. Do not edit.',
       '// </auto-generated>',
       'namespace GTA.Native', '{', '\tpublic enum Hash : ulong', '\t{']
started = False
for l in src.splitlines():
    if not started:
        started = 'enum class Hash' in l
        continue
    st = l.strip()
    if st == '{':
        continue
    if st.startswith('};'):
        break
    out.append(('\t\t' + st) if st else '')
out += ['\t}', '}']
open(os.path.join(here, 'Core', 'NativeHashes.g.cs'), 'w', encoding='utf-8').write('\n'.join(out) + '\n')
