// Generated by Tools/GTANetwork.TypeGen from GTANetwork.dll (in-game client). Do not edit; run the generator (types/README.md).
/// <reference path="./shared.d.ts" />

interface ScriptContext {
    readonly onResourceStart: HostEvent<ScriptContextEmptyEvent>;
    readonly onResourceStop: HostEvent<ScriptContextEmptyEvent>;
    readonly onUpdate: HostEvent<ScriptContextEmptyEvent>;
    readonly onKeyDown: HostEvent<(sender: unknown, e: KeyEventArgs) => void>;
    readonly onKeyUp: HostEvent<(sender: unknown, e: KeyEventArgs) => void>;
    readonly onServerEventTrigger: HostEvent<ScriptContextServerEventTrigger>;
    readonly onChatMessage: HostEvent<ScriptContextChatEvent>;
    readonly onChatCommand: HostEvent<ScriptContextChatEvent>;
    readonly onEntityStreamIn: HostEvent<ScriptContextStreamEvent>;
    readonly onEntityStreamOut: HostEvent<ScriptContextStreamEvent>;
    readonly onEntityDataChange: HostEvent<ScriptContextDataChangedEvent>;
    readonly onCustomDataReceived: HostEvent<ScriptContextCustomDataReceived>;
    readonly onPlayerDeath: HostEvent<ScriptContextPlayerKilledEvent>;
    readonly onPlayerRespawn: HostEvent<ScriptContextEmptyEvent>;
    readonly onPlayerPickup: HostEvent<ScriptContextEntityEvent>;
    readonly onPlayerEnterVehicle: HostEvent<ScriptContextEntityEvent>;
    readonly onPlayerExitVehicle: HostEvent<ScriptContextEntityEvent>;
    readonly onVehicleHealthChange: HostEvent<ScriptContextIntChangeEvent>;
    readonly onVehicleDoorBreak: HostEvent<ScriptContextIntChangeEvent>;
    readonly onVehicleWindowSmash: HostEvent<ScriptContextIntChangeEvent>;
    readonly onPlayerHealthChange: HostEvent<ScriptContextIntChangeEvent>;
    readonly onPlayerArmorChange: HostEvent<ScriptContextIntChangeEvent>;
    readonly onPlayerWeaponSwitch: HostEvent<ScriptContextIntChangeEvent>;
    readonly onPlayerModelChange: HostEvent<ScriptContextIntChangeEvent>;
    readonly onVehicleSirenToggle: HostEvent<ScriptContextEmptyEvent>;
    readonly onPlayerDetonateStickies: HostEvent<ScriptContextEmptyEvent>;
    readonly onVehicleTyreBurst: HostEvent<ScriptContextIntChangeEvent>;
    readonly onLocalPlayerDamaged: HostEvent<ScriptContextPlayerDamageEvent>;
    readonly onLocalPlayerMeleeHit: HostEvent<ScriptContextPlayerMeleeDamageEvent>;
    readonly onLocalPlayerShoot: HostEvent<ScriptContextWeaponShootEvent>;
    startCoroutine(target: unknown): void;
    showCursor(show: boolean): void;
    isCursorShown(): boolean;
    setSetting(name: string, value: unknown): void;
    getSetting(name: string): unknown;
    doesSettingExist(name: string): boolean;
    removeSetting(name: string): void;
    registerChatOverride(): JavascriptChat;
    createCamera(position: Vector3, rotation: Vector3): GlobalCamera;
    setActiveCamera(camera: GlobalCamera): void;
    setGameplayCameraActive(): void;
    getActiveCamera(): GlobalCamera;
    setCameraShake(cam: GlobalCamera, shakeType: string, amplitute: number): void;
    stopCameraShake(cam: GlobalCamera): void;
    isCameraShaking(cam: GlobalCamera): boolean;
    setCameraPosition(cam: GlobalCamera, pos: Vector3): void;
    getCameraPosition(cam: GlobalCamera): Vector3;
    setCameraRotation(cam: GlobalCamera, rotation: Vector3): void;
    getCameraRotation(cam: GlobalCamera): Vector3;
    setCameraFov(cam: GlobalCamera, fov: number): void;
    getCameraFov(cam: GlobalCamera): number;
    pointCameraAtPosition(cam: GlobalCamera, pos: Vector3): void;
    pointCameraAtEntity(cam: GlobalCamera, ent: LocalHandle, offset: Vector3): void;
    pointCameraAtEntityBone(cam: GlobalCamera, ent: LocalHandle, bone: number, offset: Vector3): void;
    stopCameraPointing(cam: GlobalCamera): void;
    attachCameraToEntity(cam: GlobalCamera, ent: LocalHandle, offset: Vector3): void;
    attachCameraToEntityBone(cam: GlobalCamera, ent: LocalHandle, bone: number, offset: Vector3): void;
    detachCamera(cam: GlobalCamera): void;
    interpolateCameras(from: GlobalCamera, to: GlobalCamera, duration: number, easepos: boolean, easerot: boolean): void;
    getCursorPosition(): PointF;
    getCursorPositionMantainRatio(): PointF;
    worldToScreen(pos: Vector3): PointF;
    worldToScreenMantainRatio(pos: Vector3): PointF;
    getCurrentResourceName(): string;
    screenToWorld(pos: PointF): Vector3;
    screenToWorldMantainRatio(pos: PointF): Vector3;
    screenToWorld(pos: PointF, camPos: Vector3, camRot: Vector3): Vector3;
    screenToWorldMantainRatio(pos: PointF, camPos: Vector3, camrot: Vector3): Vector3;
    createRaycast(start: Vector3, end: Vector3, flag: number, ignoreEntity: LocalHandle | null): ScriptContextRaycast;
    getGameplayCamPos(): Vector3;
    getGameplayCamRot(): Vector3;
    getGameplayCamDir(): Vector3;
    setCanOpenChat(show: boolean): void;
    getCanOpenChat(): boolean;
    setDisplayWastedShard(show: boolean): void;
    getDisplayWastedShard(): boolean;
    createCefBrowser(width: number, height: number, local?: boolean, focus?: boolean): Browser;
    setCefBrowserFocus(browser: Browser, focus: boolean): void;
    destroyCefBrowser(browser: Browser): void;
    isCefBrowserInitialized(browser: Browser): boolean;
    waitUntilCefBrowserInit(browser: Browser): void;
    waitUntilCefBrowserLoaded(browser: Browser): void;
    setCefBrowserSize(browser: Browser, width: number, height: number): void;
    getCefBrowserSize(browser: Browser): Size;
    setCefBrowserHeadless(browser: Browser, headless: boolean): void;
    getCefBrowserHeadless(browser: Browser): boolean;
    setCefBrowserPosition(browser: Browser, xPos: number, yPos: number): void;
    getCefBrowserPosition(browser: Browser): Point;
    verifyIntegrityOfCache(): void;
    loadPageCefBrowser(browser: Browser, uri: string): void;
    loadHtmlCefBrowser(browser: Browser, html: string): void;
    goBackCefBrowser(browser: Browser): void;
    isCefBrowserLoading(browser: Browser): boolean;
    setCefDrawState(state: boolean): void;
    setCefFramerate(browser: Browser, fps: number): void;
    getGameFramerate(): number;
    isCefDrawEnabled(): boolean;
    callNative(hash: string, ...args: unknown[]): void;
    returnNative(hash: string, returnType: number, ...args: unknown[]): unknown;
    setUiColor(r: number, g: number, b: number): void;
    getHashKey(input: string): number;
    setEntitySyncedData(entity: LocalHandle, key: string, data: unknown): boolean;
    resetEntitySyncedData(entity: LocalHandle, key: string): void;
    hasEntitySyncedData(entity: LocalHandle, key: string): boolean;
    getEntitySyncedData(entity: LocalHandle, key: string): unknown;
    getAllEntitySyncedData(entity: LocalHandle): string[];
    setWorldSyncedData(key: string, data: unknown): boolean;
    resetWorldSyncedData(key: string): void;
    hasWorldSyncedData(key: string): boolean;
    getWorldSyncedData(key: string): unknown;
    getAllWorldSyncedData(): string[];
    getGamePlayer(): number;
    getLocalPlayer(): LocalHandle;
    getEntityPosition(entity: LocalHandle): Vector3;
    getEntityRotation(entity: LocalHandle): Vector3;
    getEntityVelocity(entity: LocalHandle): Vector3;
    getVehicleHealth(entity: LocalHandle): number;
    getVehicleRPM(entity: LocalHandle): number;
    isPlayerInAnyVehicle(player: LocalHandle): boolean;
    isPlayerOnFire(player: LocalHandle): boolean;
    isPlayerParachuting(player: LocalHandle): boolean;
    isPlayerInFreefall(player: LocalHandle): boolean;
    isPlayerAiming(player: LocalHandle): boolean;
    isPlayerShooting(player: LocalHandle): boolean;
    isPlayerReloading(player: LocalHandle): boolean;
    isPlayerInCover(player: LocalHandle): boolean;
    isPlayerOnLadder(player: LocalHandle): boolean;
    getPlayerAimingPoint(player: LocalHandle): Vector3;
    isPlayerDead(player: LocalHandle): boolean;
    doesEntityExist(entity: LocalHandle): boolean;
    setEntityInvincible(entity: LocalHandle, invincible: boolean): void;
    getEntityInvincible(entity: LocalHandle): boolean;
    getLocalPlayerInvincible(): boolean;
    createParticleEffectOnPosition(ptfxLibrary: string, ptfxName: string, position: Vector3, rotation: Vector3, scale: number): void;
    createParticleEffectOnEntity(ptfxLibrary: string, ptfxName: string, entity: LocalHandle, offset: Vector3, rotation: Vector3, scale: number, boneIndex?: number): void;
    createExplosion(explosionType: number, position: Vector3, damageScale: number): void;
    createOwnedExplosion(owner: LocalHandle, explosionType: number, position: Vector3, damageScale: number): void;
    createProjectile(weapon: number, start: Vector3, target: Vector3, damage: number, speed?: number, dimension?: number): void;
    createOwnedProjectile(owner: LocalHandle, weapon: number, start: Vector3, target: Vector3, damage: number, speed?: number, dimension?: number): void;
    setVehicleLivery(vehicle: LocalHandle, livery: number): void;
    getVehicleLivery(vehicle: LocalHandle): number;
    setVehicleLocked(vehicle: LocalHandle, locked: boolean): void;
    getVehicleLocked(vehicle: LocalHandle): boolean;
    getVehicleTrailer(vehicle: LocalHandle): LocalHandle;
    getVehicleTraileredBy(vehicle: LocalHandle): LocalHandle;
    getVehicleSirenState(vehicle: LocalHandle): boolean;
    isVehicleTyrePopped(vehicle: LocalHandle, tyre: number): boolean;
    popVehicleTyre(vehicle: LocalHandle, tyre: number, pop: boolean): void;
    isVehicleDoorBroken(vehicle: LocalHandle, door: number): boolean;
    setVehicleDoorState(vehicle: LocalHandle, door: number, open: boolean): void;
    getVehicleDoorState(vehicle: LocalHandle, door: number): boolean;
    breakVehicleTyre(vehicle: LocalHandle, door: number, breakDoor: boolean): void;
    isVehicleWindowBroken(vehicle: LocalHandle, window: number): boolean;
    breakVehicleWindow(vehicle: LocalHandle, window: number, breakWindow: boolean): void;
    setVehicleExtra(vehicle: LocalHandle, slot: number, enabled: boolean): void;
    getVehicleExtra(vehicle: LocalHandle, slot: number): boolean;
    setVehicleNumberPlate(vehicle: LocalHandle, plate: string): void;
    getVehicleNumberPlate(vehicle: LocalHandle): string;
    setVehicleEngineStatus(vehicle: LocalHandle, turnedOn: boolean): void;
    getVehicleEngineStatus(vehicle: LocalHandle): boolean;
    setVehicleSpecialLightStatus(vehicle: LocalHandle, status: boolean): void;
    getVehicleSpecialLightStatus(vehicle: LocalHandle): boolean;
    setEntityCollisionless(entity: LocalHandle, status: boolean): void;
    getEntityCollisionless(vehicle: LocalHandle): boolean;
    setVehicleMod(vehicle: LocalHandle, slot: number, modType: number): void;
    getVehicleMod(vehicle: LocalHandle, slot: number): number;
    removeVehicleMod(vehicle: LocalHandle, slot: number): void;
    setVehicleBulletproofTyres(vehicle: LocalHandle, bulletproof: boolean): void;
    getVehicleBulletproofTyres(vehicle: LocalHandle): boolean;
    setVehicleNumberPlateStyle(vehicle: LocalHandle, style: number): void;
    getVehicleNumberPlateStyle(vehicle: LocalHandle): number;
    setVehiclePearlescentColor(vehicle: LocalHandle, color: number): void;
    getVehiclePearlescentColor(vehicle: LocalHandle): number;
    setVehicleWheelColor(vehicle: LocalHandle, color: number): void;
    getVehicleWheelColor(vehicle: LocalHandle): number;
    setVehicleWheelType(vehicle: LocalHandle, type_: number): void;
    getVehicleWheelType(vehicle: LocalHandle): number;
    setVehicleModColor1(vehicle: LocalHandle, r: number, g: number, b: number): void;
    setVehicleModColor2(vehicle: LocalHandle, r: number, g: number, b: number): void;
    setVehicleTyreSmokeColor(vehicle: LocalHandle, r: number, g: number, b: number): void;
    setVehicleWindowTint(vehicle: LocalHandle, type_: number): void;
    getVehicleWindowTint(vehicle: LocalHandle): number;
    setVehicleEnginePowerMultiplier(vehicle: LocalHandle, mult: number): void;
    getVehicleEnginePowerMultiplier(vehicle: LocalHandle): number;
    setVehicleEngineTorqueMultiplier(vehicle: LocalHandle, mult: number): void;
    getVehicleEngineTorqueMultiplier(vehicle: LocalHandle): number;
    setVehicleNeonState(vehicle: LocalHandle, slot: number, turnedOn: boolean): void;
    getVehicleNeonState(vehicle: LocalHandle, slot: number): boolean;
    setVehicleNeonColor(vehicle: LocalHandle, r: number, g: number, b: number): void;
    setVehicleDashboardColor(vehicle: LocalHandle, type_: number): void;
    getVehicleDashboardColor(vehicle: LocalHandle): number;
    setVehicleTrimColor(vehicle: LocalHandle, type_: number): void;
    getVehicleTrimColor(vehicle: LocalHandle): number;
    getVehicleDisplayName(model: number): string;
    getVehicleMaxSpeed(model: number): number;
    getVehicleMaxBraking(model: number): number;
    getVehicleMaxTraction(model: number): number;
    getVehicleMaxAcceleration(model: number): number;
    getVehicleMaxOccupants(model: number): number;
    getVehicleClass(model: number): number;
    detonatePlayerStickies(): void;
    setPlayerNametag(player: LocalHandle, text: string): void;
    resetPlayerNametag(player: LocalHandle): void;
    setPlayerNametagVisible(player: LocalHandle, show: boolean): void;
    getPlayerNametagVisible(player: LocalHandle): boolean;
    setPlayerNametagColor(player: LocalHandle, r: number, g: number, b: number): void;
    resetPlayerNametagColor(player: LocalHandle): void;
    setPlayerSkin(model: number): void;
    setPlayerDefaultClothes(): void;
    setPlayerTeam(team: number): void;
    getPlayerTeam(): number;
    playPlayerScenario(name: string): void;
    playPlayerAnimation(animDict: string, animName: string, flag: number, duration?: number): void;
    stopPlayerAnimation(): void;
    setVehiclePrimaryColor(vehicle: LocalHandle, color: number): void;
    setVehicleSecondaryColor(vehicle: LocalHandle, color: number): void;
    setVehicleCustomPrimaryColor(vehicle: LocalHandle, r: number, g: number, b: number): void;
    setVehicleCustomSecondaryColor(vehicle: LocalHandle, r: number, g: number, b: number): void;
    getVehicleCustomPrimaryColor(vehicle: LocalHandle): Color;
    getVehicleCustomSecondaryColor(vehicle: LocalHandle): Color;
    getVehiclePrimaryColor(vehicle: LocalHandle): number;
    getVehicleSecondaryColor(vehicle: LocalHandle): number;
    setPlayerClothes(player: LocalHandle, slot: number, drawable: number, texture: number): void;
    setPlayerAccessory(player: LocalHandle, slot: number, drawable: number, texture: number): void;
    clearPlayerAccessory(player: LocalHandle, slot: number): void;
    vehicleNameToModel(modelName: string): number;
    pedNameToModel(modelName: string): number;
    pickupNameToModel(modelName: string): number;
    weaponNameToModel(modelName: string): number;
    loadInterior(pos: Vector3): void;
    clearPlayerTasks(): void;
    setEntityPositionFrozen(entity: LocalHandle, frozen: boolean): void;
    setEntityVelocity(entity: LocalHandle, velocity: Vector3): void;
    getPlayerVehicleSeat(player: LocalHandle): number;
    getPlayerSeatbelt(player: LocalHandle): boolean;
    setPlayerWeaponTint(weapon: number, tint: number): void;
    getPlayerWeaponTint(weapon: number): number;
    givePlayerWeaponComponent(weapon: number, component: number): void;
    removePlayerWeaponComponent(weapon: number, component: number): void;
    hasPlayerWeaponComponent(weapon: number, component: number): boolean;
    getAllWeaponComponents(weapon: WeaponHash): WeaponComponentHash[];
    getPlayerCurrentWeapon(): number;
    disconnect(reason: string): void;
    setEntityPosition(ent: LocalHandle, pos: Vector3, ground?: boolean): void;
    setEntityRotation(ent: LocalHandle, rot: Vector3): void;
    setPlayerIntoVehicle(vehicle: LocalHandle, seat: number): void;
    setPlayerHealth(health: number): void;
    getPlayerHealth(player: LocalHandle): number;
    setTextLabelText(label: LocalHandle, text: string): void;
    setTextLabelColor(textLabel: LocalHandle, alpha: number, r: number, g: number, b: number): void;
    getTextLabelColor(textLabel: LocalHandle): Color;
    setTextLabelSeethrough(handle: LocalHandle, seethrough: boolean): void;
    getTextLabelSeethrough(handle: LocalHandle): boolean;
    getOffsetInWorldCoords(entity: LocalHandle, offset: Vector3): Vector3;
    getOffsetFromWorldCoords(entity: LocalHandle, pos: Vector3): Vector3;
    drawLine(start: Vector3, end: Vector3, a: number, r: number, g: number, b: number): void;
    playSoundFrontEnd(soundName: string, soundSetName: string): void;
    isEntityOnScreen(entity: LocalHandle): boolean;
    displayHelpTextThisFrame(text: string): void;
    showShard(text: string, timeout?: number): void;
    showColorShard(text: string, description: string, color1: number, color2: number, time?: number): void;
    showWeaponPurchasedShard(text: string, weaponName: string, weapon: number, time?: number): void;
    loadConfig(config: string): XmlGroup;
    fromJson(json: string): unknown;
    toJson(data: unknown): string;
    sendChatMessage(sender: string, text: string): void;
    sendChatMessage(text: string): void;
    getScreenResolutionMantainRatio(): SizeF;
    getScreenResolutionMaintainRatio(): SizeF;
    getScreenResolution(): Size;
    getScreenResolutionAccurate(): Size2;
    sendNotification(text: string): void;
    displaySubtitle(text: string): void;
    displaySubtitle(text: string, duration: number): void;
    formatTime(ms: number, format: string): string;
    setPlayerInvincible(invinc: boolean): void;
    setPlayerWantedLevel(wantedLevel: number): void;
    getPlayerWantedLevel(): number;
    getPlayerInvincible(): boolean;
    setPlayerArmor(armor: number): void;
    getPlayerArmor(player: LocalHandle): number;
    getStreamedPlayers(): LocalHandle[];
    getStreamedVehicles(): LocalHandle[];
    getStreamedObjects(): LocalHandle[];
    getStreamedPickups(): LocalHandle[];
    getStreamedPeds(): LocalHandle[];
    getStreamedMarkers(): LocalHandle[];
    getStreamedTextLabels(): LocalHandle[];
    getAllPlayers(): LocalHandle[];
    getAllVehicles(): LocalHandle[];
    getAllObjects(): LocalHandle[];
    getAllPickups(): LocalHandle[];
    getAllPeds(): LocalHandle[];
    getAllMarkers(): LocalHandle[];
    getAllTextLabels(): LocalHandle[];
    getPlayerVehicle(player: LocalHandle): LocalHandle;
    explodeVehicle(vehicle: LocalHandle): void;
    getPlayerByName(name: string): LocalHandle;
    getPlayerName(player: LocalHandle, cache?: boolean): string;
    forceSendAimData(force: boolean): void;
    isAimDataForced(): boolean;
    getPlayerAimCoords(player: LocalHandle): Vector3;
    getPlayerPing(player: LocalHandle, cache?: boolean): number;
    createVehicle(model: number, pos: Vector3, rot: Vector3): LocalHandle;
    createPed(model: number, pos: Vector3, rot: Vector3): LocalHandle;
    createBlip(pos: Vector3): LocalHandle;
    setBlipPosition(blip: LocalHandle, pos: Vector3): void;
    getBlipPosition(blip: LocalHandle): Vector3;
    getWaypointPosition(): Vector3;
    isWaypointSet(): boolean;
    setWaypoint(x: number, y: number): void;
    removeWaypoint(): void;
    setBlipColor(blip: LocalHandle, color: number): void;
    getBlipColor(blip: LocalHandle): number;
    setBlipSprite(blip: LocalHandle, sprite: number): void;
    getBlipSprite(blip: LocalHandle): number;
    setBlipName(blip: LocalHandle, name: string): void;
    getBlipName(blip: LocalHandle): string;
    setBlipTransparency(blip: LocalHandle, alpha: number): void;
    getBlipTransparency(blip: LocalHandle): number;
    setBlipShortRange(blip: LocalHandle, shortRange: boolean): void;
    getBlipShortRange(blip: LocalHandle): boolean;
    showBlipRoute(blip: LocalHandle, show: boolean): void;
    setBlipScale(blip: LocalHandle, scale: number): void;
    getBlipScale(blip: LocalHandle): number;
    setBlipRouteVisible(blip: LocalHandle, visible: boolean): void;
    getBlipRouteVisible(blip: LocalHandle): boolean;
    setBlipRouteColor(blip: LocalHandle, color: number): void;
    getBlipRouteColor(blip: LocalHandle): number;
    setChatVisible(display: boolean): void;
    getChatVisible(): boolean;
    getAveragePacketSize(): number;
    getBytesSentPerSecond(): number;
    getBytesReceivedPerSecond(): number;
    requestControlOfPlayer(player: LocalHandle): void;
    stopControlOfPlayer(player: LocalHandle): void;
    setHudVisible(visible: boolean): void;
    isSpectating(): boolean;
    getHudVisible(): boolean;
    createMarker(markerType: number, pos: Vector3, dir: Vector3, rot: Vector3, scale: Vector3, r: number, g: number, b: number, alpha: number, bobUpAndDown?: boolean): LocalHandle;
    setMarkerType(marker: LocalHandle, type_: number): void;
    getMarkerType(marker: LocalHandle): number;
    setMarkerBobUpAndDown(marker: LocalHandle, state: boolean): void;
    getMarkerBobUpAndDown(marker: LocalHandle): boolean;
    setMarkerColor(marker: LocalHandle, alpha: number, r: number, g: number, b: number): void;
    getMarkerColor(marker: LocalHandle): Color;
    setMarkerScale(marker: LocalHandle, scale: Vector3): void;
    getMarkerScale(marker: LocalHandle): Vector3;
    setMarkerDirection(marker: LocalHandle, dir: Vector3): void;
    getMarkerDirection(marker: LocalHandle): Vector3;
    deleteEntity(handle: LocalHandle): void;
    attachEntity(ent1: LocalHandle, ent2: LocalHandle, bone: string, positionOffset: Vector3, rotationOffset: Vector3): void;
    detachEntity(ent: LocalHandle): void;
    isEntityAttachedToAnything(ent: LocalHandle): boolean;
    isEntityAttachedToEntity(from: LocalHandle, to: LocalHandle): boolean;
    createTextLabel(text: string, pos: Vector3, range: number, size: number, entitySeethrough?: boolean): LocalHandle;
    lerpVector(start: Vector3, end: Vector3, currentTime: number, duration: number): Vector3;
    lerpFloat(start: number, end: number, currentTime: number, duration: number): number;
    isInRangeOf(entity: Vector3, destination: Vector3, range: number): boolean;
    dxDrawTexture(path: string, pos: Point, size: Size, rotation?: number, r?: number, g?: number, b?: number, a?: number): void;
    drawGameTexture(dict: string, txtName: string, x: number, y: number, width: number, height: number, heading: number, r: number, g: number, b: number, alpha: number): void;
    drawRectangle(xPos: number, yPos: number, wSize: number, hSize: number, r: number, g: number, b: number, alpha: number): void;
    drawText(caption: string, xPos: number, yPos: number, scale: number, r: number, g: number, b: number, alpha: number, font: number, justify: number, shadow: boolean, outline: boolean, wordWrap: number): void;
    addTextElement(caption: string, x: number, y: number, scale: number, r: number, g: number, b: number, a: number, font: number, alignment: number): UIResText;
    getGameTime(): number;
    getGlobalTime(): number;
    angleBetween(from: Vector3, to: Vector3): number;
    isPed(ent: LocalHandle): boolean;
    isVehicle(ent: LocalHandle): boolean;
    isProp(ent: LocalHandle): boolean;
    sleep(ms: number): void;
    startAudio(path: string, looped?: boolean): void;
    pauseAudio(): void;
    resumeAudio(): void;
    setAudioTime(seconds: number): void;
    getAudioTime(): number;
    isAudioPlaying(): boolean;
    setGameVolume(vol: number): void;
    isAudioInitialized(): boolean;
    stopAudio(): void;
    triggerServerEvent(eventName: string, ...arguments_: unknown[]): void;
    toString(obj: unknown): string;
    getBoneName(bone: number): string;
    getWeaponName(weapon: number): string;
    getVehicleModelName(model: number): string;
    createMenu(title: string, x: number, y: number, anchor: number): UIMenu;
    createMenu(title: string, subtitle: string, x: number, y: number, anchor: number, enableBanner?: boolean, disableControls?: boolean, scaleWithSafezone?: boolean): UIMenu;
    createMenuItem(label: string, description: string): UIMenuItem;
    createColoredItem(label: string, description: string, hexColor: string, hexHighlightColor: string): UIMenuColoredItem;
    createCheckboxItem(label: string, description: string, isChecked: boolean): UIMenuCheckboxItem;
    createListItem(label: string, description: string, items: string[], index: number): UIMenuListItem;
    getMenuPool(): MenuPool;
    drawMenu(menu: UIMenu): void;
    setMenuBannerSprite(menu: UIMenu, spritedict: string, spritename: string): void;
    setMenuBannerTexture(menu: UIMenu, path: string): void;
    setMenuBannerRectangle(menu: UIMenu, alpha: number, red: number, green: number, blue: number): void;
    setMenuTitle(menu: UIMenu, title: string): void;
    setMenuSubtitle(menu: UIMenu, text: string): void;
    getUserInput(defaultText: string, maxlen?: number): string;
    isControlJustPressed(control: number): boolean;
    isControlPressed(control: number): boolean;
    isDisabledControlJustReleased(control: number): boolean;
    isDisabledControlJustPressed(control: number): boolean;
    isDisabledControlPressed(control: number): boolean;
    isControlJustReleased(control: number): boolean;
    disableControlThisFrame(control: number): void;
    enableControlThisFrame(control: number): void;
    disableAllControlsThisFrame(): void;
    getControlNormal(control: number): number;
    getDisabledControlNormal(control: number): number;
    setControlNormal(control: number, value: number): void;
    isChatOpen(): boolean;
    loadAnimationDict(dict: string): void;
    loadModel(model: number): void;
    requestScaleform(scaleformName: string): unknown /* GTA.Scaleform */;
    renderScaleform(sc: unknown /* GTA.Scaleform */, x: number, y: number, w: number, h: number): void;
    setEntityTransparency(entity: LocalHandle, alpha: number): void;
    getEntityType(entity: LocalHandle): number;
    getEntityTransparency(entity: LocalHandle): number;
    setEntityDimension(entity: LocalHandle, dimension: number): void;
    getEntityDimension(entity: LocalHandle): number;
    getEntityModel(entity: LocalHandle): number;
    getEntityBoneIndexByName(entity: LocalHandle, boneName: string): number;
    removeAllPlayerWeapons(): void;
    doesPlayerHaveWeapon(weapon: number): boolean;
    removePlayerWeapon(weapon: number): void;
    setWeather(weather: number): void;
    getWeather(): number;
    resetWeather(): void;
    setTime(hours: number, minutes: number): void;
    getTime(): TimeSpan;
    resetTime(): void;
    playScreenEffect(effectName: string, duration: number, looped: boolean): void;
    playPoliceReport(reportName: string): void;
    getStreetName(position: Vector3): string;
    getZoneName(position: Vector3): string;
    getZoneNameLabel(position: Vector3): string;
    getGroundHeight(position: Vector3): number;
    getGameText(labelName: string): string;
    toggleGameAIEntities(state: boolean): void;
    toggleSnow(): boolean;
}
type ScriptContextEmptyEvent = () => void;
type ScriptContextServerEventTrigger = (eventName: string, arguments_: unknown[]) => void;
type ScriptContextChatEvent = (msg: string) => void;
type ScriptContextStreamEvent = (item: LocalHandle, entityType: number) => void;
type ScriptContextDataChangedEvent = (entity: LocalHandle, key: string, oldValue: unknown) => void;
type ScriptContextCustomDataReceived = (data: string) => void;
type ScriptContextPlayerKilledEvent = (killer: LocalHandle, weapon: number) => void;
type ScriptContextEntityEvent = (entity: LocalHandle) => void;
type ScriptContextIntChangeEvent = (oldValue: number) => void;
type ScriptContextPlayerDamageEvent = (attacker: LocalHandle, weaponUsed: number, boneHit: number) => void;
type ScriptContextPlayerMeleeDamageEvent = (attacker: LocalHandle, weaponUsed: number) => void;
type ScriptContextWeaponShootEvent = (weaponUsed: number, aimCoords: Vector3) => void;
interface JavascriptChat {
    SanitationLevel: number;
    IsFocused: boolean;
    CurrentInput: string;
    readonly OnComplete: HostEvent<(sender: unknown, e: EventArgs) => void>;
    readonly onTick: HostEvent<ScriptContextEmptyEvent>;
    readonly onKeyDown: HostEvent<(sender: unknown, e: KeyEventArgs) => void>;
    readonly onFocusChange: HostEvent<BooleanEvent>;
    readonly onInit: HostEvent<ScriptContextEmptyEvent>;
    readonly onClearRequest: HostEvent<ScriptContextEmptyEvent>;
    readonly onAddMessageRequest: HostEvent<MessageEvent>;
    readonly onCharInput: HostEvent<IntegerEvent>;
    readonly onChatHideRequest: HostEvent<BooleanEvent>;
    Tick(): void;
    sendMessage(msg: string): void;
    OnKeyDown(key: Keys): void;
    Init(): void;
    Clear(): void;
    AddMessage(sender: string, message: string): void;
}
interface GlobalCamera {
}
interface LocalHandle {
    HandleType: HandleType;
    readonly Raw: number;
    readonly Value: number;
    readonly IsNull: boolean;
    Properties<T>(): T;
}
interface ScriptContextRaycast {
    readonly didHitAnything: boolean;
    readonly didHitEntity: boolean;
    readonly hitEntity: LocalHandle;
    readonly hitCoords: Vector3;
}
interface Browser {
    /** Input and focus of the browser, or null until it exists in the host. */
    readonly Host: BrowserInput;
    Headless: boolean;
    Position: Point;
    Pinned: PointF[];
    Size: Size;
    GetHost(): BrowserInput;
    eval_(code: string): void;
    call(method: string, ...arguments_: unknown[]): void;
}
interface XmlGroup {
    getSubgroup(groupName: string): XmlGroup;
    hasAnyElementOfType(typeName: string): boolean;
    getNumberOfElementsOfType(typeName: string): number;
    getElementsByType(typeName: string): xmlElement[];
    getElementByType(typeName: string): xmlElement;
}
interface UIResText {
    TextAlignment: UIResTextAlignment;
    DropShadow: boolean;
    Outline: boolean;
    WordWrap: Size;
    Enabled: boolean;
    Color: Color;
    Position: PointF;
    Scale: number;
    Font: Font;
    Caption: string;
    Alignment: Alignment;
    Shadow: boolean;
    WrapWidth: number;
    Centered: boolean;
    readonly Width: number;
    readonly ScaledWidth: number;
    Draw(offset: SizeF): void;
    Draw(): void;
    ScaledDraw(): void;
    ScaledDraw(offset: SizeF): void;
}
interface UIMenu {
    AUDIO_LIBRARY: string;
    AUDIO_UPDOWN: string;
    AUDIO_LEFTRIGHT: string;
    AUDIO_SELECT: string;
    AUDIO_BACK: string;
    AUDIO_ERROR: string;
    MenuItems: UIMenuItem[];
    MouseEdgeEnabled: boolean;
    ControlDisablingEnabled: boolean;
    ResetCursorOnOpen: boolean;
    FormatDescriptions: boolean;
    MouseControlsEnabled: boolean;
    ScaleWithSafezone: boolean;
    readonly Children: Map<UIMenuItem, UIMenu>;
    readonly WidthOffset: number;
    Visible: boolean;
    CurrentSelection: number;
    readonly Size: number;
    readonly Title: UIResText;
    readonly Subtitle: UIResText;
    CounterPretext: string;
    ParentMenu: UIMenu;
    ParentItem: UIMenuItem;
    readonly OnIndexChange: HostEvent<IndexChangedEvent>;
    readonly OnListChange: HostEvent<ListChangedEvent>;
    readonly OnCheckboxChange: HostEvent<CheckboxChangeEvent>;
    readonly OnItemSelect: HostEvent<ItemSelectEvent>;
    readonly OnMenuClose: HostEvent<MenuCloseEvent>;
    readonly OnMenuChange: HostEvent<MenuChangeEvent>;
    SetMenuWidthOffset(widthOffset: number): void;
    DisableInstructionalButtons(disable: boolean): void;
    SetBannerType(spriteBanner: Sprite): void;
    SetBannerType(rectangle: UIResRectangle): void;
    SetBannerType(pathToCustomSprite: string): void;
    AddItem(item: UIMenuItem): void;
    InsertItem(item: UIMenuItem, position: number): void;
    RemoveItemAt(index: number): void;
    RefreshIndex(): void;
    Clear(): void;
    Draw(): void;
    IsMouseInListItemArrows(item: UIMenuListItem, topLeft: Point, safezone: Point): number;
    GoUpOverflow(): void;
    GoUp(): void;
    GoDownOverflow(): void;
    GoDown(): void;
    GoLeft(): void;
    GoRight(): void;
    SelectItem(): void;
    GoBack(): void;
    BindMenuToItem(menuToBind: UIMenu, itemToBindTo: UIMenuItem): void;
    ReleaseMenuFromItem(releaseFrom: UIMenuItem): boolean;
    ProcessMouse(): void;
    SetKey(control: UIMenuMenuControls, keyToSet: Keys): void;
    SetKey(control: UIMenuMenuControls, gtaControl: Control): void;
    SetKey(control: UIMenuMenuControls, gtaControl: Control, controlIndex: number): void;
    ResetKey(control: UIMenuMenuControls): void;
    HasControlJustBeenPressed(control: UIMenuMenuControls, key?: Keys): boolean;
    HasControlJustBeenReleased(control: UIMenuMenuControls, key?: Keys): boolean;
    IsControlBeingPressed(control: UIMenuMenuControls, key?: Keys): boolean;
    ProcessControl(key?: Keys): void;
    ProcessKey(key: Keys): void;
    AddInstructionalButton(button: InstructionalButton): void;
    RemoveInstructionalButton(button: InstructionalButton): void;
    UpdateScaleform(): void;
}
interface UIMenuItem {
    Selected: boolean;
    Hovered: boolean;
    Description: string;
    Enabled: boolean;
    Offset: Point;
    Text: string;
    readonly RightLabel: string;
    readonly LeftBadge: UIMenuItemBadgeStyle;
    readonly RightBadge: UIMenuItemBadgeStyle;
    Parent: UIMenu;
    readonly Activated: HostEvent<ItemActivatedEvent>;
    Position(y: number): void;
    ProcessControl(control: UIMenuMenuControls): boolean;
    Draw(): void;
    SetLeftBadge(badge: UIMenuItemBadgeStyle): void;
    SetRightBadge(badge: UIMenuItemBadgeStyle): void;
    SetRightLabel(text: string): void;
}
interface UIMenuColoredItem extends UIMenuItem {
    MainColor: Color;
    HighlightColor: Color;
    TextColor: Color;
    HighlightedTextColor: Color;
    Draw(): void;
}
interface UIMenuCheckboxItem extends UIMenuItem {
    Checked: boolean;
    readonly CheckboxEvent: HostEvent<ItemCheckboxEvent>;
    Position(y: number): void;
    ProcessControl(control: UIMenuMenuControls): boolean;
    Draw(): void;
    CheckboxEventTrigger(): void;
    SetRightBadge(badge: UIMenuItemBadgeStyle): void;
    SetRightLabel(text: string): void;
}
interface UIMenuListItem extends UIMenuItem {
    Index: number;
    readonly OnListChanged: HostEvent<ItemListEvent>;
    Position(y: number): void;
    ItemToIndex(item: unknown): number;
    IndexToItem(index: number): unknown;
    ProcessControl(control: UIMenuMenuControls): boolean;
    Draw(): void;
    SetRightBadge(badge: UIMenuItemBadgeStyle): void;
    SetRightLabel(text: string): void;
}
interface MenuPool {
    MouseEdgeEnabled: boolean;
    ControlDisablingEnabled: boolean;
    ResetCursorOnOpen: boolean;
    FormatDescriptions: boolean;
    AUDIO_LIBRARY: string;
    AUDIO_UPDOWN: string;
    AUDIO_SELECT: string;
    AUDIO_BACK: string;
    AUDIO_ERROR: string;
    WidthOffset: number;
    CounterPretext: string;
    DisableInstructionalButtons: boolean;
    Add(menu: UIMenu): void;
    AddSubMenu(menu: UIMenu, text: string): UIMenu;
    AddSubMenu(menu: UIMenu, text: string, description: string): UIMenu;
    RefreshIndex(): void;
    ToList(): UIMenu[];
    ProcessControl(): void;
    ProcessKey(key: Keys): void;
    ProcessMouse(): void;
    Draw(): void;
    IsAnyMenuOpen(): boolean;
    ProcessMenus(): void;
    CloseAllMenus(): void;
    SetBannerType(bannerType: Sprite): void;
    SetBannerType(bannerType: UIResRectangle): void;
    SetBannerType(bannerPath: string): void;
    SetKey(menuControl: UIMenuMenuControls, control: Control): void;
    SetKey(menuControl: UIMenuMenuControls, control: Control, controllerIndex: number): void;
    SetKey(menuControl: UIMenuMenuControls, control: Keys): void;
    ResetKey(menuControl: UIMenuMenuControls): void;
}
declare enum UIMenuMenuControls {
    Up = 0,
    Down = 1,
    Left = 2,
    Right = 3,
    Select = 4,
    Back = 5,
}
declare enum UIMenuItemBadgeStyle {
    None = 0,
    BronzeMedal = 1,
    GoldMedal = 2,
    SilverMedal = 3,
    Alert = 4,
    Crown = 5,
    Ammo = 6,
    Armour = 7,
    Barber = 8,
    Clothes = 9,
    Franklin = 10,
    Bike = 11,
    Car = 12,
    Gun = 13,
    Heart = 14,
    Makeup = 15,
    Mask = 16,
    Michael = 17,
    Star = 18,
    Tatoo = 19,
    Trevor = 20,
    Lock = 21,
    Tick = 22,
}
type BooleanEvent = (value: boolean) => void;
type MessageEvent = (msg: string, hasColor: boolean, r: number, g: number, b: number) => void;
type IntegerEvent = (value: number) => void;
declare enum HandleType {
    GameHandle = 0,
    LocalHandle = 1,
    NetHandle = 2,
}
interface BrowserInput {
    WindowlessFrameRate: number;
    SetFocus(focus: boolean): void;
    SendMouseMoveEvent(mouseEvent: MouseEvent, mouseLeave: boolean): void;
    SendMouseClickEvent(mouseEvent: MouseEvent, button: MouseButtonType, mouseUp: boolean, clickCount: number): void;
    SendMouseWheelEvent(mouseEvent: MouseEvent, deltaX: number, deltaY: number): void;
    SendKeyEvent(keyEvent: KeyEvent): void;
}
interface xmlElement {
    name: string;
    hasElementData(elementName: string): boolean;
    getElementData(elementName: string, returnType: number): unknown;
}
declare enum UIResTextAlignment {
    Left = 0,
    Centered = 1,
    Right = 2,
}
type IndexChangedEvent = (sender: UIMenu, newIndex: number) => void;
type ListChangedEvent = (sender: UIMenu, listItem: UIMenuListItem, newIndex: number) => void;
type CheckboxChangeEvent = (sender: UIMenu, checkboxItem: UIMenuCheckboxItem, Checked: boolean) => void;
type ItemSelectEvent = (sender: UIMenu, selectedItem: UIMenuItem, index: number) => void;
type MenuCloseEvent = (sender: UIMenu) => void;
type MenuChangeEvent = (oldMenu: UIMenu, newMenu: UIMenu, forward: boolean) => void;
interface Sprite {
    Position: Point;
    Size: Size;
    Color: Color;
    Visible: boolean;
    Heading: number;
    TextureName: string;
    TextureDict: string;
    Draw(): void;
}
interface UIResRectangle {
    Enabled: boolean;
    Color: Color;
    Position: PointF;
    Centered: boolean;
    Size: SizeF;
    Draw(offset: SizeF): void;
    Draw(): void;
    ScaledDraw(): void;
    ScaledDraw(offset: SizeF): void;
}
interface InstructionalButton {
    Text: string;
    readonly ItemBind: UIMenuItem;
    BindToItem(item: UIMenuItem): void;
    GetButtonId(): string;
}
type ItemActivatedEvent = (sender: UIMenu, selectedItem: UIMenuItem) => void;
type ItemCheckboxEvent = (sender: UIMenuCheckboxItem, Checked: boolean) => void;
type ItemListEvent = (sender: UIMenuListItem, newIndex: number) => void;
interface MouseEvent {
    X: number;
    Y: number;
    Modifiers: CefEventFlags;
}
declare enum MouseButtonType {
    Left = 0,
    Middle = 1,
    Right = 2,
}
interface KeyEvent {
    Type: KeyEventType;
    Modifiers: CefEventFlags;
    WindowsKeyCode: number;
    NativeKeyCode: number;
}
declare enum CefEventFlags {
    None = 0,
    CapsLockOn = 1,
    ShiftDown = 2,
    ControlDown = 4,
    AltDown = 8,
    LeftMouseButton = 16,
    MiddleMouseButton = 32,
    RightMouseButton = 64,
    CommandDown = 128,
    NumLockOn = 256,
    IsKeyPad = 512,
    IsLeft = 1024,
    IsRight = 2048,
}
declare enum KeyEventType {
    RawKeyDown = 0,
    KeyDown = 1,
    KeyUp = 2,
    Char = 3,
}

/** The scripting API object of the running script (one ScriptContext per script file). */
declare const API: ScriptContext;
/** Other scripts of the same resource (by file name without extension) and their exported members. */
declare const resource: Record<string, any>;
/** Exported members of every running resource, by resource name. */
declare const exported: Record<string, any>;
/** Host types the client registers with AddHostType; generic host types are constructed as `new (List(Int32))()`. */
declare const List: any;
declare const Dictionary: any;
declare const Enumerable: any;
// `String` is a host type too, but it is a JavaScript global already and is not redeclared here.
declare const Int32: { new (value?: any): number };
declare const Bool: { new (value?: any): boolean };
declare const Double: { new (value?: any): number };
declare const Float: { new (value?: any): number };
declare const Vector3: { new (): Vector3; new (x: number, y: number, z: number): Vector3; };
declare const Matrix4: { new (): Matrix4; };
declare const Point: { new (x: number, y: number): Point; };
declare const PointF: { new (x: number, y: number): PointF; };
declare const Size: { new (width: number, height: number): Size; };
declare const Size2: { new (width: number, height: number): Size2; };
declare const KeyEventArgs: { new (keyData: Keys): KeyEventArgs; };
declare const CancelEventArgs: { new (cancel?: boolean): CancelEventArgs; };
declare const menuControl: typeof UIMenuMenuControls;
declare const BadgeStyle: typeof UIMenuItemBadgeStyle;
